version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://backend
